name: 'Python Versionator'
description: 'Autoupdate the python package versions in your Github action matrix.'
inputs:

  action_path:
    description: 'The path to the action file to update.'
    required: true

  package:
    description: 'The python package whose version is being tracked.'
    required: true

  project_description:
    description: "A description of the project- this can be a full markdown text."
    required: true
    default: "project_description"

  readme_path:
    description: 'The path to the README file to update.'
    required: true
    default: "${{ github.workspace }}/README.md"

  template_directory:
    description: 'The path to the README template.'
    required: true
    default: ""

  repository:
    description: 'The repository, for updating the readme.'
    required: true
    default: ${{ github.repository }}

  organization:
    description: 'The organization, for updating the readme.'
    required: true
    default: ${{ github.repository_owner }}

  git_name:
    description: 'The name to use as the author of the commit.'
    required: true
    default: ${{ github.repository_owner }}

  git_email:
    description: 'The email to use for the author of the commit.'
    required: true
    default: "python-versionator@tedivm.com"

  max_versions:
    description: 'The maximum number of versions (from most current back) to inject into the action.'
    required: true
    default: '10'

  update_python:
    description: 'When enabled python versions will also be updated.'
    required: true
    default: 'true'


runs:
  using: "composite"
  steps:

    - name: Update Package Versions
      shell: bash
      run: "bash ${{ github.action_path }}/scripts/update_packages.sh \"${{ inputs.package }}\" \"${{ inputs.action_path }}\""
      env:
        MAX_VERSIONS: ${{ inputs.max_versions }}

    - name: Update Python Versions
      shell: bash
      run: "[[ \"${{inputs.update_python}}\" == \"true\" ]] && sed -i 's/python_versions:.*/python_versions: [\"3.6\", \"3.7\", \"3.8\", \"3.9\", \"3.10\"] /' \"${{ inputs.action_path }}\""

    - uses: "actions/setup-python@v2"

    - name: "Install Jinja2"
      shell: bash
      run: "python -m pip install jinja2"

    - name: "Update README.md"
      shell: bash
      run: "bash ${{ github.action_path }}/scripts/update_readme.sh > ${{ inputs.readme_path }}"
      env:
        TEMPLATE_DIRECTORY: ${{ inputs.template_directory }}
        PROJECT_NAME: ${{ inputs.package }}
        PROJECT_DESCRIPTION: ${{ inputs.project_description }}
        PACKAGE_VERSIONS: ${{join(steps.package_versions.outputs.*, ' ')}}
        PYTHON_VERSIONS: "3.6 3.7 3.8 3.9 3.10"
        MAX_VERSIONS: ${{ inputs.max_versions }}
        ORGANIZATION: ${{ inputs.organization }}
        REPOSITORY: ${{ inputs.repository }}

    - name: "Push"
      shell: bash
      run: "bash ${{ github.action_path }}/scripts/push.sh"
      env:
        GIT_USER: ${{ inputs.git_name }}
        GIT_EMAIL: ${{ inputs.git_email }}
        ACTION_PATH: ${{ inputs.action_path }}
        README_PATH: ${{ inputs.readme_path }}
